version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: "06:00"

  - package-ecosystem: "pip"
    directories:
      - "**/*"
    schedule:
      interval: daily
      time: "06:00"